apiVersion: v1
kind: Secret
metadata:
    name: jellyfin-config-volsync-pcloud
    namespace: media
type: Opaque
stringData:
    RESTIC_PASSWORD: ENC[AES256_GCM,data:yXZBTORpd6uTJrSJ+IJgXQDtwshQbtntfAGmp8JIt1pUHGJkhdT6uw==,iv:mLRl6mEtFDefk0K2rdvDrUdqm/BvI4HLYe33v79P0r0=,tag:AGAA7s3hp5ELvyMdsKKQRg==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:lVO8U18k2CRG21oTKySqovBMHfO38Dx2o+UyxeOgkzV2WvxyDcA7GBLwZyb4IeI+qrLbbxF7QP6CQoYZow/Yr9Qx781OGplUOkfO,iv:YTcnR5MuoINAaxTJnUsy25EJLXRds3kzPJ5UedwY9FM=,tag:G70y+MFZ2MYa9ce3uMvPvQ==,type:str]
    RCLONE_CONFIG_PCLOUD_TYPE: ENC[AES256_GCM,data:2dgsv3Zi,iv:0eLAWnPx4NqfCZFiygG9uQWezLuio5ytUOMauVXSGT8=,tag:yZEqpcO0s2t+4yfvSmUr6w==,type:str]
    RCLONE_CONFIG_PCLOUD_HOSTNAME: ENC[AES256_GCM,data:0gpK07f+hzScICU5Y1E=,iv:Nn3maCyVZZo4F57WusulL5VJSn3vzizLBmNau7PanP0=,tag:2i1PHvNVbLi1FvUMubN8vQ==,type:str]
    RCLONE_CONFIG_PCLOUD_TOKEN: ENC[AES256_GCM,data:WoHl6AHEccwSk/8ChZZOZ2WiIpXn0ZiaTjLT0BZgXuuT+m0iB98V1wH7JA/ioDoyix69ArCvwzsQaNOsJJ9sGrzVfNiQ4j8WxTT+gZo3sUxSv+TMEMbbkTro0gPVr07F0O8arrMukcx34pIeH9oLG93SpCuzmTzBEYcgXfuy,iv:xu8aFmfrdmPe5mg/qJ5DUF5EyUS8F7sNLFr90mus4Mo=,tag:kSdGDCwFyPGegsHQxUXE1A==,type:str]
sops:
    age:
        - recipient: age198qlalug6g4kvmp3xypzzsr5lvw36wexemc2jn220t29l7nak33qft2q7y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPbC9rWUF4Y0kza29XWmd5
            VkNFZzNGNzBNQ2RCaFpSc2tRY29FWHV2MEQwCkExSVBHblk1QVl6YmRSRkswQk1U
            MTVtMUJpUDFJN2M2STF0OWhXWElmSDQKLS0tIDc5Mk1YcGFjMVZrVHBVYmdsdmk0
            Y0R1czVQU2lFTUhmTFdHQTBrM3g0RUUKmxSJYfTfApbm5pY6SXI/qnkAM6506FAk
            12hwAGvex3uKM6sO24+lxUjAEZdCQ7aztxP8SH23amDkJXLAASsOlA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T17:48:22Z"
    mac: ENC[AES256_GCM,data:mlJo3+De5ySix60crAMl5J9RtimyATMgLfw7NwiXmybYaSDw+VD71lOAArCWjrsNlbF9tT5o5QmXN8y0hmGlqdQ+zA7QWOu1AwMqlAM2/uYhWShofkM366p7zg6ql4vqiGhJRMAiLFuwobKWtmxYSD2/1KIdBOrXagpXWN6YL94=,iv:+3BtQMZwZdAVkbRuCtfhk8OxUiDCB/3QXRHrVABZ/mQ=,tag:ez4CEeLEGJG3j6AGm9vWcg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.12.1
