apiVersion: v1
kind: Secret
metadata:
    name: kavita-config-volsync-pcloud
    namespace: kavita
type: Opaque
stringData:
    RESTIC_PASSWORD: ENC[AES256_GCM,data:L9ZsdQpynhxFCKwJhQTK6aHC5VjSRlS8T0LtWOIMsfxSF0DgtSxYzw==,iv:s8JJRyQwUIiEEH/DW/3PKhA/oZ2atQcEOIRl6Bno82o=,tag:BArCfpdKK0R8R6ub6Za35w==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:mctXm7OXppsYtnnGx4Nq8O3oOpkVj5ni+NcvAIUUNoAUjv7ssVWyy5MJsJ9YELAVNQoWERL8n/WWIEe5hDoBRxtDGDTKfzZEaQ==,iv:K1MEdF8XgbbDaK/1aVYMF72fwsEzZTbi2E7DhsBKamI=,tag:V8uo/VbCA+JOxuuVzslIwg==,type:str]
    RCLONE_CONFIG_PCLOUD_TYPE: ENC[AES256_GCM,data:2y6QD1mD,iv:+iagZni/UpC1WlxYNZlsOELlBcN1pCcbQH8Kz7S3WJ8=,tag:xXWYJ2yDlZRc9OsbZOgD7Q==,type:str]
    RCLONE_CONFIG_PCLOUD_HOSTNAME: ENC[AES256_GCM,data:/pZ6zG57JdpVuqF1Aeg=,iv:Lu33Crgk9Tf0p5TDOb+Rd5O0meyDcHKME0P3HcDAs7o=,tag:rET7p1RecCw8ZSKbkgSogw==,type:str]
    RCLONE_CONFIG_PCLOUD_TOKEN: ENC[AES256_GCM,data:QKnarsAcZ35JU0ZItdEXN/V/vw6s8RQ1lzK035M4OPcPE86+diaXijHLYQUJuzeRheLr0DMkjsIJNA56oImXQvXrnd/JiM4wtz6yGWeFBbjGyy7ySWAzUEM3ky1MyuHrhmTS5XQQ0/dh+ITTVeurunbwiE0dm+MB61X3McN8,iv:lnchxomkls/A6sI9vVtB/OXl5P4eyzhCoDofQE42WhE=,tag:S7vIXKDl0hIGUv/UhgIY2w==,type:str]
sops:
    age:
        - recipient: age198qlalug6g4kvmp3xypzzsr5lvw36wexemc2jn220t29l7nak33qft2q7y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBVUplV1VlaUZCSlBZcjRC
            aDFqTU42amN5SFQxbyt3aGdHSGdCZGpYOEVvCmlQMS9oa1hleGJUVytCZDNpN1la
            Y2ZJdEZ1OTZRbXM5Q1V3SmEwSUJkNEkKLS0tIHNZSTZLY1dlcW1RTjFsVnhkQzdP
            SlRsQUJJa1JVZDF2SFEvSVhnaUs0TlEKSI+jxDkcGLSEIMQLkdIWhyiyvVmOCxP+
            LLDVeEIhA7lgc7UtS0YqZTqUMZYtOWfAoIj7Iy8yRiaai3wnV2OFrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T18:03:00Z"
    mac: ENC[AES256_GCM,data:gZqdimYeMwTruqgMHODmvSJUY6Set5CxzUOiP6GRFi/9sSwnZxs0GL5fVLr7l+6LhRv81zsdsNc8+akY09ygCdLl7kXtIo4LL60bQAXv7GeAM1kgJ6PShWGVdHdk9vqOkaZ5FnNyMsMRL37MVayCxaoCvUD5pAM+oqCGH51JvAs=,iv:XmCTUA0raYxEg12IogYO+O1oOGEC8BhbF+jPVWwPqDY=,tag:pqh6DlVZnPcUNoCHRMyIBg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.12.1
