apiVersion: v1
kind: Secret
metadata:
  name: kavita-config-volsync-minio
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ${VOLSYNC_BACKUP_MAIN_ACCESSKEY}
  AWS_SECRET_ACCESS_KEY: ${VOLSYNC_BACKUP_MAIN_SECRETKEY}
  RESTIC_PASSWORD: ${VOLSYNC_BACKUP_MAIN_ENCRKEY}
  RESTIC_REPOSITORY: s3:${VOLSYNC_BACKUP_MAIN_URL}/${VOLSYNC_BACKUP_MAIN_BUCKET}/kavita/volsync/config-volsync-minio
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: kavita-config-minio-dest
spec:
  trigger:
    manual: restore-once
  restic:
    repository: kavita-config-volsync-minio
    destinationPVC: kavita-config
    copyMethod: Direct
    cacheCapacity: 10Gi
    cleanupCachePVC: false
    accessModes:
      - ReadWriteOnce
    moverSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 568
