apiVersion: v1
kind: Secret
metadata:
    name: radarr-config-volsync-pcloud
    namespace: media
type: Opaque
stringData:
    RESTIC_PASSWORD: ENC[AES256_GCM,data:425fiFQHaQk799k4Wb6c5ZSWRBm+LoGmdl3BpGdAlZOqHZ8UIlul2g==,iv:veR86cu3fTWji1HYobQlVauzqm+kmVAA2f0MPX0k4EE=,tag:k52pA2dWhaPX3LJdtZShZg==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:+5HdE28mDlCvJk46FI4qJdwrpPAdxHHHqty5aU78jBnCywhr5GRYKO+piuizbw8nWu8cgpaFdoAIBz8YzLgsl2/AnVognvc0Bw==,iv:Eigsu94Mz4DE2K64rWRrZEPCIchnGP4Ey3Y6dyot4Lw=,tag:IizW4KngG5vhLUPLjuYQHA==,type:str]
    RCLONE_CONFIG_PCLOUD_TYPE: ENC[AES256_GCM,data:pu2ylsHY,iv:eOxx0+cAZjTxXRpBo/lH8U2Dw96Ls/oB0wkUhRaTSpY=,tag:sy6jV/buPKHe8o+hou0SIA==,type:str]
    RCLONE_CONFIG_PCLOUD_HOSTNAME: ENC[AES256_GCM,data:QvOWPfrFvLQYz5IuTZY=,iv:LCnsju7KToaS/nMlTKEP2gLVphhgfCpyG22GxmVsxUg=,tag:+mjIRVHv6KKx/wHJthUlIQ==,type:str]
    RCLONE_CONFIG_PCLOUD_TOKEN: ENC[AES256_GCM,data:mYnUxHAI1PCzNiIuunvYos6kfkw6UWrdVHyNw7BqhYkSDJiCYNYpjYpPbfRrrHf1wHmiEmdZHqfEHzpEVmgYFI/9ETO5yHon86adhaKOJPoAcZTj7zEQK0R7F9/HotAkct+2lLNz5XiaMFqDXb2NT7Udf7VHMJL0wc3O7W5x,iv:C2kfLPl9bvx5D95PT/QJsPxPuP2RVfDIMG6ZZxOHeBs=,tag:bWTTRv94J46OYz6n/NIl6g==,type:str]
sops:
    age:
        - recipient: age198qlalug6g4kvmp3xypzzsr5lvw36wexemc2jn220t29l7nak33qft2q7y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmQlRXVURmUmUvSlBnMDY0
            a0xISVFpMmxXVXdhcVFzZzdQRVowNXFJNDNRCkR5MXBDcXBNZ0M2MjAzWlF3YUNq
            Y0tncndOanJDQzViYlhmMEU3MFJrOTAKLS0tIE44eHlTbTJNNW9pQVdLZmEyN1gy
            dks4MUxRck9idC9TSk5lT2ltSXJYQUUK5Kw9dQoos4ufb+2WbbiyexQmmuKecsdl
            9Arb+u3Ex65FEToO2MpkYPCERseh6qE0odjBv60BCnY/mzFLyZk9yg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T17:48:23Z"
    mac: ENC[AES256_GCM,data:7WemJ3zuRLCx9djnIGqjg6dWuP/cTPp7JU8cO6vl1yqRiZqCkhCqgRZtRSsIonGrvLU3j6VUz18wZi1gELFpSRU16F+eiQXANA3lwkMttAJamB3orNJ7Hbt5LjRefy3Fmivhq1vYHQFmBBri6hf7Xvj8YQ7hws90WXeHYHO1lyc=,iv:WzP8iGfjVqsbWt/KcJ9xdxaiHCVlb+ZlbgBNVxUUNCE=,tag:IDcswXjt6VUVgMqDaJasNg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.12.1
