apiVersion: v1
kind: Secret
metadata:
    name: hoarder-app-template-data-volsync-pcloud
    namespace: hoarder
type: Opaque
stringData:
    RESTIC_PASSWORD: ENC[AES256_GCM,data:5sP+CrjUqJezMLyZPlVdZ3qYxrsLAvIQqq5uwDn/N4S+IVSWeMvDiw==,iv:CrCOiwCpyLQbtH1GVdeLebJFx6PB0iAz1u/7mDfJFUs=,tag:Dk6Bxq9tHBVL4oLZsontAA==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:xFvl/vpOTRkTnTU6vijAOv5lB+9J0gaBvEIzG2dstNR2ND8TYmaGm9cMFy6hx0RuIFPWz1BNnhDA5WnACB4Z3at2ScFw+XFSDMxVbv3Diw3jYJfj0Q==,iv:2DBZWJxIGNGf554SXQSMNii64FBglV9NJPkSvNoviF4=,tag:jsZcjz9rH+7HG7DE8/8tDA==,type:str]
    RCLONE_CONFIG_PCLOUD_TYPE: ENC[AES256_GCM,data:Rzn69Y5r,iv:ZddDnylyvF+pVlP8WDox/muDrOcrrXkUjuTanKK/nUw=,tag:jcd8LwthXiuc+ZffJpLRBQ==,type:str]
    RCLONE_CONFIG_PCLOUD_HOSTNAME: ENC[AES256_GCM,data:W7X1vxxSKJS71YQnFaM=,iv:Zd6gP6rqWR2LmgI1HE9WVdEp4ahvfGZNh+N56wYhO8E=,tag:Y9HEf/hdgN6dd6Rhm5/s5g==,type:str]
    RCLONE_CONFIG_PCLOUD_TOKEN: ENC[AES256_GCM,data:2Zd/bASGqLFOhojXudyB1w+Viy6TV6kI6NYz+DZ/fEdASYxh2n5ATxdgyqJMS4yqZ/jLnqo7NXfHTZxXyoJATzOXuPSvkaO3j+wo5o40Xog2kpMqrchfPVYP3H+BTlwuYK7aQoaGeJijT2yVDrVcePSLwMA9Ou9n/SHFMyZ4,iv:8cgukUW/gZKxISNWze/qj2OGS6mCce4lpytTm8i3pfA=,tag:2rqd6mWYTUoxkMSDWQuusQ==,type:str]
sops:
    age:
        - recipient: age198qlalug6g4kvmp3xypzzsr5lvw36wexemc2jn220t29l7nak33qft2q7y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxQzVRNDdGNlNzbFNjbkpK
            K1lqU2w5bkN6Q0ZETmdQaE1iZHE1TnVTZndnCnA3alJCOWk2N2FKandITTR3SWhj
            b2tnb3ZXN2pITjNmaGh4aGRCYjVEUVUKLS0tIFgvS1ZTSU4rT2FmWkc1bDJJSms0
            dHUyOU4xaTd4akNZTzlMc0hMWlFqOVEKwik9UuhouIxxnJvvU7h9ebINyVjwiCop
            ArUPvbOGuNs5QmetJHOznmPN96/nxlG5TgZDKJ0fp9L3e7TK4dupwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T03:37:23Z"
    mac: ENC[AES256_GCM,data:/I0y8rmh8fwAvZ3IzO3d/UBt/tUpRq7BFGrnq1os1ZQfDN+oQFRdpyBuEEqQVS9qEe8iNQnSzymLZbiue6uqVE3EGtcADsfwpWQbIWjaJnNvha2ImwcvGraCHVP/opzOaSOp0Q/PGwQA2mZWnY8PHEs0439P5MRwG8a3hwOopdg=,iv:bRe2lstJzw9u26R3xpsO5ZtLkY9jDqnrBqA3pD5gCQY=,tag:XvOzk2eG5DEgyrpfQsAZQg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.12.1
