apiVersion: v1
kind: Secret
metadata:
    name: hoarder-app-template-meili-data-volsync-pcloud
    namespace: hoarder
type: Opaque
stringData:
    RESTIC_PASSWORD: ENC[AES256_GCM,data:FnL005ATxxEiRbzT4U7zLiBGkEzmsz+JHPX9UErPJKQzapKNdy8kMA==,iv:KwjK5w6Pz2dldpEpTfLHb+neMow15QKW3B+Cyu/8Kak=,tag:7KLIOPxIOg1vAyMh+7D92A==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:huXN/ngvF67MNnxtb7LgsmRvL+spDUAsqudUNww5k8OhGpnjxBVAEDheQRZOrjTfQcrejFRbRfzIcU0bp8Abg7af76hCNAvRplgof+RZ+M2YM1X0GlCK9WEPJw==,iv:ejlbeYs2qdsY+gwKRiGof1A4mIquduN9FsdV1DlCAag=,tag:M5AURf8pFuAgVgG9IUWfxw==,type:str]
    RCLONE_CONFIG_PCLOUD_TYPE: ENC[AES256_GCM,data:iYGFYVmZ,iv:U/EOdzVXLl009LzcxoI5M+5C48ynCp9lEDeX3C7CGT4=,tag:WLxpwtcyKxo5PM8p9e3FHg==,type:str]
    RCLONE_CONFIG_PCLOUD_HOSTNAME: ENC[AES256_GCM,data:TDAoRSCeph/DGpduQGQ=,iv:Hcduq4IeUheKN1ZwenOGekWHFFh+kQvGTGbbMXHPz70=,tag:g5iyubGuTvJWS2J9xCzCbw==,type:str]
    RCLONE_CONFIG_PCLOUD_TOKEN: ENC[AES256_GCM,data:xR1aK4RrkLvWl6d0GWw8EKQ/xGnB0gLtQQUUkorMGeIPMGtIjOpffEpjXoG8UzFgHpMYwvOZnH1OMS/ouVR83Go+LgVZnWsgMemwc68FRfxorLz9Tw9kiq6mZCnSu4LUE5gegXj2+kxQvE8qvYbvZU3uOrxH+Qq1UQuDw/am,iv:uE5uA1jBUcBJfJvRL9zblorPlxYmdA6/eEAL2FFj3yQ=,tag:7A3tc0L13oHhHRshbk6nWw==,type:str]
sops:
    age:
        - recipient: age198qlalug6g4kvmp3xypzzsr5lvw36wexemc2jn220t29l7nak33qft2q7y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKbFJwYzkzVkZjL0phYjlP
            ZWpxb3owY211Wk1JOURJUGtPR0x3UWF1amxnCnpUa0xaWGlQcllsdm85RTJoTjZS
            RWtJamNycDcyN1lMNTdmclAxUzkzY2cKLS0tIGowTy9EZG1UbmJGZThqMVRyUURl
            d2xYZlZsZVozUEhUbzVFSkdtT3dKR2sKFrORGReKKeIrn29PSmuyuDr3XBq26XZU
            LhUqfBDIMQFhmGDXQYwrciCmnmE8HhdKPx7ZDsVQeUtRpVuQmwGIfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T03:37:23Z"
    mac: ENC[AES256_GCM,data:b924rqRwcn1wt96x/1z5KzwPyTxpFt2L7v0v3ZGWWZouQvfiprmuj5pxgTiPuWiDhgcNlE3I7aDrB6K7P9HU19dWKWMDmFGZq61hQ+Rp39oSR7rEIMV4JuFrnwznXGtD1KK75bj7dj5dmp1fJtMEATBAjtlbkl2RdJ2ZnXfkzg0=,iv:meSysYNnXDUacfiubmDm5ocN5YMnJhnxs5sqgdzasu0=,tag:Vq0ErprwC7QMN39Cm/VxEg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.12.1
