apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hoarder-app-template-data-longhorn
  namespace: hoarder
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hoarder-app-template-meili-data-longhorn
  namespace: hoarder
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Gi
