apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: hoarder-app-template-data-pcloud
spec:
  sourcePVC: hoarder-app-template-data-longhorn
  trigger:
    manual: pcloud-hoarder-data-20260319
  restic:
    repository: hoarder-app-template-data-volsync-pcloud
    copyMethod: Snapshot
    pruneIntervalDays: 7
    cacheCapacity: 10Gi
    retain:
      daily: 3
      weekly: 4
      monthly: 2
      within: 30d
    accessModes:
      - ReadWriteOnce
    moverSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 568
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: hoarder-app-template-meili-data-pcloud
spec:
  sourcePVC: hoarder-app-template-meili-data-longhorn
  trigger:
    manual: pcloud-hoarder-meili-20260319
  restic:
    repository: hoarder-app-template-meili-data-volsync-pcloud
    copyMethod: Snapshot
    pruneIntervalDays: 7
    cacheCapacity: 10Gi
    retain:
      daily: 3
      weekly: 4
      monthly: 2
      within: 30d
    accessModes:
      - ReadWriteOnce
    moverSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 568
