apiVersion: v1
kind: Secret
metadata:
    name: changedetection-io-datastore-volsync-pcloud
    namespace: changedetection-io
type: Opaque
stringData:
    RESTIC_PASSWORD: ENC[AES256_GCM,data:NOwHjam+3dFvbKHaIKntOJsGoEQx0BAx2SjzC63fibfJqGvCyRKbEw==,iv:YbZICJIjNPynuJsWI+g0/MXHjhjDwHSRQ06hdM/MUEI=,tag:ep8mBtH/CBImoU44zFcblQ==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:RQSEmlazsIfMCuLqutQz+qzpk5AaMqO1nIiZ37yKE2+Fu4/VppuS9iAI6R+5FX7PoMk8s7HM60QbDb6WuVBvz/sSpv+YPLAlKd3XF1l1IcV7j4LTnWRVtA==,iv:tyND3xTZufnXA7/XUMqCYVfZ7MfyOqS7Ep75kF0OT/A=,tag:fhTWw8JepEK/52+lxnKTaA==,type:str]
    RCLONE_CONFIG_PCLOUD_TYPE: ENC[AES256_GCM,data:Gm1u6dpG,iv:2mHciOwJVcam/4exEB+Q0Fb5d5it54Xv8VcHzqusc1A=,tag:BERqQLFBwcMGXXhj6Uj9zQ==,type:str]
    RCLONE_CONFIG_PCLOUD_HOSTNAME: ENC[AES256_GCM,data:jlhJV+IKl0V9hft1+aI=,iv:pbhdkJwdSSKF0tq8WN6NVYM36/saO3dmz98aEMpMWrA=,tag:xHaUOj2q4mksm+ezRLdl2Q==,type:str]
    RCLONE_CONFIG_PCLOUD_TOKEN: ENC[AES256_GCM,data:Aabj2Th3YW1RDm3hBqS98VFJib9JQI5aa+Cqfmbo0DmXeGG/xM7WnkQKdQjnpgQjUeq3yuamQwAAOfw2B0xe0pAdSUjDpSFQ+wFohH+hj1mvUG91VW/uoCuDP9GmRJqBkzUjCxTS3bEMTOsbAoMSFOwNSG9k6wUzqQktmMzM,iv:93tiAGWDC0wAqM+fEQ96CAHIKjItwrCmC0MoSOBAOMc=,tag:m7e0SOBSSRZsPkI4ScLILQ==,type:str]
sops:
    age:
        - recipient: age198qlalug6g4kvmp3xypzzsr5lvw36wexemc2jn220t29l7nak33qft2q7y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxYm9JUlQ5dmNPVm9Fc3dX
            YlRQTWR4OTNrcXFuSnQxaDVkNHVTZFZ6Vml3Cnp6Z1NnY29XbEl1cEcwM0pURXJy
            Vmg4eExTRFRjdmtoWi95MU41bDZibTAKLS0tIDVBUCs5cy9FKzJ4c3JXK2hVZ1dT
            Vlh0c3M5UVBycFNDb0k3dCtiVEJIU2sKmnYtyWSCE2w4KZVrIKZ4oxZnglUhdPNk
            62bwIjzgFYsZpXF+iLuzTaXeK9oJ0Q/hSqutrHofOnuWNVnl53nzig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T18:03:00Z"
    mac: ENC[AES256_GCM,data:zurusIYp9Qp0mVV0AxSSHk91VC6gQK+LV7qDVzme5vJqYwY4afRWMFjz8T1Oy8tApxa9NBQOHPjOrDRB1zNmEU+koVNsmwKJ9Ha2e9v+GzRY29HaO4rpY7tm50lPN/71dRAJ67oeO4Gp0CTOwiapl8QEQiAQ/b6TM9fJiJUSQLI=,iv:IZjlcwMkSUE2xZScLupqMcQFXFG4bmDdY8XiwnS7hHA=,tag:o+Ite0T0NBsTQ2LUZBiflA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.12.1
