apiVersion: v1
kind: ConfigMap
metadata:
  name: karakeep-configuration
data:
  # renovate: datasource=github-tags depName=karakeep-app/karakeep versioning=semver
  KARAKEEP_VERSION: "0.31.0"
  NEXTAUTH_URL: https://keep.${DOMAIN_0}
  CRAWLER_VIDEO_DOWNLOAD: "true"
  DISABLE_PASSWORD_AUTH: "true"
  DISABLE_SIGNUPS: "false"
  OAUTH_ALLOW_DANGEROUS_EMAIL_ACCOUNT_LINKING: "true"
  OAUTH_CLIENT_ID: karakeep
  OAUTH_PROVIDER_NAME: Authelia
  OAUTH_TIMEOUT: "10000"
  OAUTH_WELLKNOWN_URL: https://auth.${DOMAIN_0}/.well-known/openid-configuration
  TZ: US/Central
