apiVersion: v1
kind: Secret
metadata:
  name: karakeep-data-volsync-pcloud
  namespace: karakeep
type: Opaque
stringData:
  RESTIC_PASSWORD: ${VOLSYNC_BACKUP_MAIN_ENCRKEY}
  RESTIC_REPOSITORY: rclone:pcloud:${VOLSYNC_BACKUP_PCLOUD_REMOTE_PATH}/${VOLSYNC_BACKUP_PCLOUD_REPO_SUBPATH}/hoarder-app-template-data-volsync-pcloud
  RCLONE_CONFIG_PCLOUD_TYPE: pcloud
  RCLONE_CONFIG_PCLOUD_HOSTNAME: ${VOLSYNC_BACKUP_PCLOUD_HOSTNAME}
  RCLONE_CONFIG_PCLOUD_TOKEN: ${VOLSYNC_BACKUP_PCLOUD_TOKEN_JSON}
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: karakeep-data-pcloud
  namespace: karakeep
spec:
  sourcePVC: hoarder-app-template-data-longhorn
  trigger:
    schedule: "0 0 * * *"
  restic:
    repository: karakeep-data-volsync-pcloud
    copyMethod: Snapshot
    pruneIntervalDays: 7
    cacheCapacity: 10Gi
    retain:
      daily: ${VOLSYNC_BACKUP_RETENTION_DAILY}
      weekly: ${VOLSYNC_BACKUP_RETENTION_WEEKLY}
      monthly: ${VOLSYNC_BACKUP_RETENTION_MONTHLY}
      within: ${VOLSYNC_BACKUP_RETENTION_WITHIN}
    accessModes:
      - ReadWriteOnce
    moverSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 568
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: karakeep-data-pcloud-dest
  namespace: karakeep
spec:
  trigger:
    manual: restore
  restic:
    repository: karakeep-data-volsync-pcloud
    destinationPVC: hoarder-app-template-data-longhorn
    copyMethod: Direct
    cacheCapacity: 10Gi
    moverSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 568
---
apiVersion: v1
kind: Secret
metadata:
  name: karakeep-meili-data-volsync-pcloud
  namespace: karakeep
type: Opaque
stringData:
  RESTIC_PASSWORD: ${VOLSYNC_BACKUP_MAIN_ENCRKEY}
  RESTIC_REPOSITORY: rclone:pcloud:${VOLSYNC_BACKUP_PCLOUD_REMOTE_PATH}/${VOLSYNC_BACKUP_PCLOUD_REPO_SUBPATH}/hoarder-app-template-meili-data-volsync-pcloud
  RCLONE_CONFIG_PCLOUD_TYPE: pcloud
  RCLONE_CONFIG_PCLOUD_HOSTNAME: ${VOLSYNC_BACKUP_PCLOUD_HOSTNAME}
  RCLONE_CONFIG_PCLOUD_TOKEN: ${VOLSYNC_BACKUP_PCLOUD_TOKEN_JSON}
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: karakeep-meili-data-pcloud
  namespace: karakeep
spec:
  sourcePVC: hoarder-app-template-meili-data-longhorn
  trigger:
    schedule: "0 0 * * *"
  restic:
    repository: karakeep-meili-data-volsync-pcloud
    copyMethod: Snapshot
    pruneIntervalDays: 7
    cacheCapacity: 10Gi
    retain:
      daily: ${VOLSYNC_BACKUP_RETENTION_DAILY}
      weekly: ${VOLSYNC_BACKUP_RETENTION_WEEKLY}
      monthly: ${VOLSYNC_BACKUP_RETENTION_MONTHLY}
      within: ${VOLSYNC_BACKUP_RETENTION_WITHIN}
    accessModes:
      - ReadWriteOnce
    moverSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 568
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: karakeep-meili-data-pcloud-dest
  namespace: karakeep
spec:
  trigger:
    manual: restore
  restic:
    repository: karakeep-meili-data-volsync-pcloud
    destinationPVC: hoarder-app-template-meili-data-longhorn
    copyMethod: Direct
    cacheCapacity: 10Gi
    moverSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 568
