apiVersion: v1
kind: Secret
metadata:
    name: lldap-secret
type: Opaque
stringData:
    LLDAP_JWT_SECRET: ENC[AES256_GCM,data:0FsLQRtaljhfhe7x57mZ7NqriNFn3m06yH9PE2le4YC5M7M3ma+6e7gI2f002wsLO0Y=,iv:cnCIBdkXO11QUUDcu58BH/022OEgBgJSrvzdt0ZkgFU=,tag:6jWrnWEpZNjkyJq4n+zBag==,type:str]
sops:
    age:
        - recipient: age198qlalug6g4kvmp3xypzzsr5lvw36wexemc2jn220t29l7nak33qft2q7y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuMXpLRCsvenB4OW5rbmI4
            V1lIcy9SRkU1MkFkNUtFL08zcG0xODRvK1JrCktvQWhGdS9YU1B2aC90SnVMTmhv
            YXU0cWJVK2JoTEkySzBXWjh0OTRCNzgKLS0tIEk2K3BrWHI1U1V5YmRucmJDSEZ4
            a24zdk5kWFdGNDF5VDdzWXljRnRoVDAKlG1kmwviWdm2FN8MEX/QK5DpjkjOuEN2
            rxhYcz9ohjfMKrhHEJsgAYenBrYks2tt1iJmWFkdXCxtC/pXgG55Vw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T22:28:06Z"
    mac: ENC[AES256_GCM,data:PN7u0R8JqSZzrMdXUERweH07UrJb/VuYRpMRif15zIZycXFd495fTNlIRYHg5lE+IB1z2neAJDyWvbKFam3D08vsKL1UntntPu+sXlqMhMs53IjBoF57+pQPWOFn29PzpiOXLx55Z2BH9PUNFFAfwc0MYqFZd7mVHTIPeM/8O9A=,iv:NEApZaJ5o5L4wErrNJik13haycUKwKNzTb07T3xDyVs=,tag:Cwua9Nl5RfHSNQNZXDoz+w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.12.1
