apiVersion: v1
kind: Secret
metadata:
    name: lldap-data-volsync-pcloud
    namespace: lldap
type: Opaque
stringData:
    RESTIC_PASSWORD: ENC[AES256_GCM,data:kNKo87dC64kNnNpH0+dy09LHtauXbbgA9iZNMNC6nV0NUBgZkabzlQ==,iv:VE5DP55GQ7iRvD3bo1F6alisiED6n+SVx9VuIGiiqr8=,tag:J6cGlbBRM36rRpmOyOIB/g==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:fD337hsy67uhZB5UMzJzpiLjfx8yTtcQzeZyK8QjYJcCoMihuQ/NJXq8ErU6Jd5SvMthDdda4mMsfK95Ca6MW8KE5RDifg==,iv:/Rd7mG8StATZQG06zPv1Ylu0jW3GWLx+f4LVufrzvfU=,tag:Jl5cDMohdNYmpQ5TRjV6XQ==,type:str]
    RCLONE_CONFIG_PCLOUD_TYPE: ENC[AES256_GCM,data:+8vGxaLQ,iv:VhygBv2q3YLUH5qkAJkTkagdEzvqzXR6kLVOEOfctaQ=,tag:TXS+TlKJdG7/EbkvOFL7+g==,type:str]
    RCLONE_CONFIG_PCLOUD_HOSTNAME: ENC[AES256_GCM,data:77PdteawYfz040wcWOs=,iv:X6q+FqZ8S+C6JRfQsebBXjX9ywcMcLiaVZRfLsB/V/k=,tag:0oXprnQ8s+HEBFHpSjNN6A==,type:str]
    RCLONE_CONFIG_PCLOUD_TOKEN: ENC[AES256_GCM,data:HApDZoUD8zefBbymDNoLKD5Js3LCabj6BpAv5K2GZ5KrWdwTk7WIKpSuOEzQlAQ1w0tTiBOjZSshK8Gt2EVKZhmtIVpz3T7ujxRyTBn+mAAK1wkeYeHBk6mCJrGznq22idyCc/NkW+LjNaBCLKl/UdyFJ+ctPPj6PdUp4cSo,iv:+fAVpRjq0DClWUIhtq+BdGqw1+cmz4zNkUf1wF6de8A=,tag:HYxX+hadpDBniDs8cukTZg==,type:str]
sops:
    age:
        - recipient: age198qlalug6g4kvmp3xypzzsr5lvw36wexemc2jn220t29l7nak33qft2q7y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFdUVGQjdaV1lxRXg4MzRE
            VEgwcWtZVFpzQkpieEJCSDZOajVmcXJBZlE4Cm0vUEFVb2UwSnlZVnJyalJoUlhj
            U1pmZWNPUTcxSlJQL2RvZ1hmTC9MWmMKLS0tIEc4RTRQNTRwLzh4V2J5VTdoajJv
            cEErTjljSjZGRVpSSDZWS0x2WHhOM2cK5ULkcnkz2bibkhJtBjvIKiaM6w3eAjwq
            qvz0cJaBS8cwOpx8gbndwQnxB/dVDtdVB8Zjlp0dEt4dT1r6JJbRqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T17:48:23Z"
    mac: ENC[AES256_GCM,data:s2wA2leiFgrl+Wy/qvRz4BvT3XUmsW5PMu6g598dM6esv0Vpgcu854rUnOHvLryNLl74Rg3Xfq3SYSuRcBxn5lVb793IMgzBueSVp+Z7toP6v/EzN4mSnDu02BQ5MDXhAvUHn6zz/T0ftlCvXAuWPG561OmlRZHknfTzAwGPTaw=,iv:fDtDIToXG0AHVW11vq4u7QtHFua/g/R78QzxlsF4c8s=,tag:iZGMx9pi+RqRcsDuJ+io0w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.12.1
