apiVersion: v1
kind: Secret
metadata:
    name: ntfy-config-volsync-pcloud
    namespace: ntfy
type: Opaque
stringData:
    RESTIC_PASSWORD: ENC[AES256_GCM,data:5lSq0qphSMXaa3ooZTEYoqOUOSuBBHLYkfF4ZQjsgfURFbHuE3vCxg==,iv:r2JoHyvEU7t4ccmtaZUxo2scZ8M8bV6HnMYQRqqxGJE=,tag:R6RrxQkJZEZkmeqPPJvqdw==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:R5Xt/bnBS1Afe0wJk/C/FsixgsSLkCB9YjQt5vsPLuEm5HJpQz347GA1pCTNTthuOiiW5bpxZLO90nV+6as5AUYxxWFy03s=,iv:qFRCxbfFyJCHnI9hmXK62eTeRTCM5c6MoW3BFbHIeMg=,tag:YZbzkHZ9DBPM3FYshATZHg==,type:str]
    RCLONE_CONFIG_PCLOUD_TYPE: ENC[AES256_GCM,data:26V7gCUT,iv:R75YYqq5Ot1I7KGOuEiXa5emTqkOwC7+u7I5mMhghAU=,tag:avaQzt2w0X7Y0waAIh0ZUQ==,type:str]
    RCLONE_CONFIG_PCLOUD_HOSTNAME: ENC[AES256_GCM,data:4VgC0KdNZEkhvFTbwGQ=,iv:2VciqTnxbQ54kAdHBbX+LIcXcvHcn3brX74R8+ojlcQ=,tag:IPgx84apu/hf2dVi7OQeNw==,type:str]
    RCLONE_CONFIG_PCLOUD_TOKEN: ENC[AES256_GCM,data:YElaFN8GmJjYJqV/IKNFbiPQiF03i1Y39263r7Xz/IcRKfa+bYGWcpudlgPrKlkTZ+PHscHOvJ7X9YAqnd4E6nPSGL3FE7KklMu+lvj9jVVysAannYl9Gha/xeFiv/A4oBmC6CeRK72raCNPmsdYQG8NCTLJ+GIiXnwcDbGw,iv:Poy6g4mASnhmx69CSzAB/o+AsewqUv1U4SIxu4ZDAxw=,tag:c96WPwhTlpMs6YcTqq8Qcw==,type:str]
sops:
    age:
        - recipient: age198qlalug6g4kvmp3xypzzsr5lvw36wexemc2jn220t29l7nak33qft2q7y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsNVFzNE5NVDhEd2JlcDFj
            cHdSbHFGV0tTL0hFSjRmRFJXaURuakxra3lrCi9nTkhqUnBiSmc1b2d5NzJubW5Y
            dkN4YkNXMExybXIzR2dVUkFRTVRpcjgKLS0tIGdKK0U4T2tmdkN5ckJKUHNHT0RJ
            L1Btd1lMM1BQVTAxaUFVa0t6bVpvdGsKg5OTJeG+3S30BhcPJFEnNLDl30VNn4Ij
            jJ6A0rYCTC5jJ0js721j93IP1wiIX+QNDY/8b1nPB7+QmSINrcPuzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T18:03:00Z"
    mac: ENC[AES256_GCM,data:gO8KoYpihKE0B15vbd9DdQUDdbzE6hrwgnS/cbVIFdXf7zRpK7sRMrBC3eANrnEVGfsaVOwY+08TB5f8UeC7EgomxmkoWcZNnUStHD4YsoAt9bQIK04wZ1xNBGwolrFVVje66+Yy7yXFmNWt1EkOFLdTY4uBKMKUl47GLZZFQ5c=,iv:zcMJUlx2XT6K31Gt+iwo/uP5pybJZb+Z2hPY7jrMPeA=,tag:+nlrPDqr3ehR/mLvOrbdaQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.12.1
