apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: ntfy-config-pcloud
  namespace: ntfy
spec:
  sourcePVC: ntfy-config
  trigger:
    schedule: "0 0 * * *"
  restic:
    repository: ntfy-config-volsync-pcloud
    copyMethod: Snapshot
    pruneIntervalDays: 7
    cacheCapacity: 10Gi
    retain:
      daily: 3
      weekly: 4
      monthly: 2
      within: 30d
    accessModes:
      - ReadWriteOnce
    moverSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 568
