apiVersion: v1
kind: Secret
metadata:
    name: maintainerr-data-volsync-pcloud
    namespace: media
type: Opaque
stringData:
    RESTIC_PASSWORD: ENC[AES256_GCM,data:SBiMfGhMQboAgOKrLG0EGXpWibrzjD+cK8UTXg4aMA==,iv:7cZod/sgzolGnE0+UoqEJ7D7nDX+/er8JmTRrW/n0k8=,tag:3lqOegDhVqHazXHMKyIZrQ==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:tMs9c0V0CmlsRsjvZmi1R7aSuzIHjugDhAhmaJydZuDgldawK6YpIJU9iWK+g4SjbSmXwbBcBkU+rVIuJDfAvwpPBI+s/ttN8+/oVw==,iv:qvKev53m35LZPuEoE2SDRVJQSoq2HafLIoPPvJDVGdc=,tag:6Il8btUFWs93oX+kRj48Xw==,type:str]
    RCLONE_CONFIG_PCLOUD_TYPE: ENC[AES256_GCM,data:sqTL97n1,iv:ZKyoAoGBJeDgRqjH+DULtz+4DdojVb39PD/Us1XkjSw=,tag:0Gbscz1Pp/4zkPBMZi+C8g==,type:str]
    RCLONE_CONFIG_PCLOUD_HOSTNAME: ENC[AES256_GCM,data:hkxj2tnwwafXf5DVS84=,iv:VKkOxuh3yp+NHD/leDfzb8Jd3Q4l3WL19YHPlwqp3n4=,tag:MsPKw8i7EpzD1BTnwsNjJQ==,type:str]
    RCLONE_CONFIG_PCLOUD_TOKEN: ENC[AES256_GCM,data:FOVaexPutsxeKB0DxDkZCs/pywET7Fn+DxBpEYti4rAEQ+nFoG8k5g9AoK4gxLtuR2OGDMR8vCtSZqhPBEXBAY0PdVx88FznFx2Fv8kyo8muWe7DCXUoq4tEi8NEoaTGqcH9wz0puK/DnFPwjlJpF/5WAU4sLmz/HyxN73H6,iv:eUPm56DnmxUSditxYoDnGER7YPHBRkGTL3+ELJLumCg=,tag:ljSnUMrB1qFi/HHzfiELXQ==,type:str]
sops:
    age:
        - recipient: age198qlalug6g4kvmp3xypzzsr5lvw36wexemc2jn220t29l7nak33qft2q7y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUUVpcGpKdEZLU1BOSkh5
            TXRpMXVZU3UxbWVyelIzOGxQNzk4emMzVlYwCmRpRFV6R2FXcXhqbHcwZlRvM2Zm
            eFk0YmU5bHNtMVV6Qm9ObE8yVVpNUmcKLS0tIFZJRG5PTDM3SHUxWi9uRzVaN2Nw
            Uy9YaUFRVGJIbHJOVVUyRVkvcHArczgK/QhzoRDJlQ9WXm0PjZbHcCNp7G485o82
            +28mfjuBQq2wiTNiLonZWZ7ISP69G4s1vVeHQcTTf0uMqOcb9xkNow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T18:03:00Z"
    mac: ENC[AES256_GCM,data:jT+v7CUo/HUhJ3tPIPsKyP0MEuvlsglDhZCRuH8LyZ9MbbS5QIprBTv8eAROmrvXbEw5eOVMwmqEIl95AN1tw/UGeYgcKt6K5vxcky8m3W3/kVoFHQguZCeXn7G5NyKqfApRBQBhKhMvPjb4V9+VlvTlCgzfPcj88JX1NXtBuPM=,iv:E5q/FFxq/4fTOlbq5pMbzd9vPerGA5aSMUhEN/Y3+Ao=,tag:2CenNP4a5MFESUfy6+C3TA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.12.1
