apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: audiobookshelf
    namespace: external-apps
spec:
    interval: 15m
    chart:
        spec:
            chart: external-service
            version: 16.18.0
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: audiobookshelf
    values:
        ingress:
            main:
                enabled: true
                ingressClassName: external
                annotations:
                    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
                hosts:
                    - host: books.${DOMAIN_0}
                      paths:
                        - path: /
                          pathType: Prefix
                integrations:
                    certManager:
                        certificateIssuer: domain-0-le-prod
                        enabled: true
                    homepage:
                        enabled: false
        release_name: audiobookshelf
        service:
            main:
                enabled: true
                type: ExternalName
                externalName: ${NAS_DOMAIN}
                ports:
                    main:
                        enabled: true
                        port: 30067
                        protocol: http
