apiVersion: v1
kind: Secret
metadata:
    name: freshrss-config-volsync-pcloud
    namespace: freshrss
type: Opaque
stringData:
    RESTIC_PASSWORD: ENC[AES256_GCM,data:eDAzmEhRQNU+0FwGtr8HakIdBpBGPVpmzWqljIHd,iv:+1nJaxWjlGBuPbeKRqMS5UfJ98fpcF8786k/dlj/dEo=,tag:2NzCJ31ZDtHuMZsIbnAWSw==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:KaHAOPQYTC9T/qT2SsKRm+K6FtlnN6+RWXa8MK0eFXTgzpHzZUcQIxhoZ9TTq+rOQJy983md3Gt38818DTZ3pFeN22kQ6Yx+PZ97fE0zuBVo+JHF7qx12V30f7WRkwSAIwWKxXwDyHc=,iv:DZxQIzZV3Ro94Tkoy0nqYRSLWKC+M0joF9KtjHzvrmY=,tag:0eo/2KnRu8lbwofu2mkPhw==,type:str]
    RCLONE_CONFIG_PCLOUD_TYPE: ENC[AES256_GCM,data:dEBvMG4W,iv:0mzr51CNCidrrBBtIzU3NBoUaEIKy81ADV8V8rfvP1M=,tag:jdRGiHzob5XLodPiXLA0fg==,type:str]
    RCLONE_CONFIG_PCLOUD_HOSTNAME: ENC[AES256_GCM,data:VHh0bfLV2m4RU0MrvMelYB8tZEI0Z9wtK8CyOxW8sFo5,iv:eNH4YGg0EwFDhg1VQMIho8V8eGA1lK6VjAd/4FCILKY=,tag:FwP0lcI6GZscYe5nLgLtIA==,type:str]
    RCLONE_CONFIG_PCLOUD_TOKEN: ENC[AES256_GCM,data:Y6dqnB48mVaYspYWnPYdrqqgmpWcNU3pC37azyJn8tBFcsw=,iv:19TciIi/UOqFpnqibA4Hfzlgq3nF2DzFHVR2J8d7G60=,tag:06uMKf7cSmb8kTorayWMaQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age198qlalug6g4kvmp3xypzzsr5lvw36wexemc2jn220t29l7nak33qft2q7y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSnZQekxFSTczR0lhRG0z
            Zm9BOFdPM2Y0NnprNkpuMVA2UlBSdzlPR1RvCkFMSVc1NUV0ZjFMWThqUnhVU3ZL
            VUZwV0sranMwM0FyS2VBWWJWMWRJVlEKLS0tIFN3WVRsdWxCaEhIbTljajdjMkNX
            S2tKaTMzQjNnTDl2MzVyR2R4b0xVTTgKh6HhZfhJFksQ7dMSiMHiW0ufVr/yZvmO
            xkPrtuqLXEhgIkXMzaEV9BaASShmEAvSwP0iEqqxz2KDevkW4goJ+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T01:50:12Z"
    mac: ENC[AES256_GCM,data:iucfSeBvQ8+d2i4G5MXIzg9s1HoMrw6ReP82aJeU1r8wSEtxwmFN8ht7wswntokG4oaBDTqGxk0yu8nNFTaXEw4rHZaGqgGvWfDtadvcZ7bvj1lO7MqRhcLD3lsyj5DanrfDLh0R5EVojdoaH7stBP0p9TqKvIjUtICQPaUzBEI=,iv:xr4v2IsIhlixd7ycqMppBaulrSm4inUztIhxkmWC2tY=,tag:1sLh91hyd01svZyR9pXOCA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
