apiVersion: v1
kind: Secret
metadata:
    name: freshrss-config-volsync-minio
    namespace: freshrss
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:TpDTj25aHAo2rzBcsLBWNCbB60s=,iv:4JDh65XDhOnWKGPdIfILfzyfj1jiHcsVHoygIqR5unY=,tag:8s7rkIp/67xbqqrasxA7pw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:wQXp2nicJJZ6oe0ZALPfZI0RoCUwByuaS/tfE3ogJgeDKADe0GELQQ==,iv:lo7fQUquIjm/N5/5BXcBgMpUltnM35O1+3pGkTg6sbM=,tag:syUsHAYHn0xtgUUJP11phQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:X4tZUBQPoUMjB+EMdNIfmWRPsPMHcnBXtlbNZiTLBUni9YyZotfTYQ==,iv:A0gTIvv04kJ7taKtUiFV46sjSjQ/x+LefZXZ/Lr/9OI=,tag:h9t5Ta55CT1kJyBy4xFQeg==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:4x6/kVEN8yFI2pGxB8MRadE0n8+Nx9u/WlvIeT5iKrKtO4MRr/lKDs4GxbDW6M6TaskW7zzKuDwH6TvTHXlCWt1fMZxNNZaMXg==,iv:PFs/R7q6dMN2xyUqFayjh5KWTuZbfbr+7DQOoqhCbN0=,tag:aQDAkVXUFb3Jr6u4iW4P3Q==,type:str]
sops:
    age:
        - recipient: age198qlalug6g4kvmp3xypzzsr5lvw36wexemc2jn220t29l7nak33qft2q7y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEU3MvQktLSXNJb3BTUm1X
            WDMrRTdTVTF1TWJacFpROXJjdDUxREpaZmdJClA2NnNsVUtSb3F3MklMVUR0Sm1a
            ZitYc2F4d28vTkdQUTdXMVNZWXEvMFEKLS0tIDR6Q09jVFNFT2o4VzBjODk5K0F3
            ZGkvbVJubDZVK2FFeW9meE0vSGxNSzAKdoXhxUJ5txIx5ohKRMP6kqge9dcmOaDU
            k4fwHNqm/BZx76sG8qqBQgrcrFRfPv0W1r/U0aiNk7QiFbwP7E6d1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T21:56:45Z"
    mac: ENC[AES256_GCM,data:FULQP2Usx0KHnnkhm3jl4WijTbzpa4g9EPznrkYCNSf1SDxclIU4jrg8nS/WSM3xC6H3/rc1/h6g2rBcMsY8M8NtnF/uhQSmOnBlQdUuYWk2BpKFb2gOM+JPGyv3FHIVagbdSb5o2g8Lsa/UYnkCxA0tBLa7zXsbkVsbpt+qumA=,iv:k/MX44dqIGOCwlb/C9s3ipSy0tGmgQe9R93YQPi45RU=,tag:xtdiRqPO5OXmH09V8qNCPg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.12.1
