apiVersion: v1
kind: Secret
metadata:
    name: freshrss-config-volsync-pcloud
    namespace: freshrss
type: Opaque
stringData:
    RESTIC_PASSWORD: ENC[AES256_GCM,data:dOq58XJBw9ugKk8Fd7qezCMGpdxWXzo6PjS4mdE1JUDxfL5WyxkEEA==,iv:om4TjIptVcmL0Kzk6KSr7ubxjcvJUq8NWvp5DCkfcoI=,tag:fdFtDrGS39NXai7SSNriLQ==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:8ASZN+NXUWU2o28sufnrbbmVf/cb+GRE8YgFdPrp3f5IfZFEXk+ErqFNmR3A9foHcPR0OtqqdwhL5RO6,iv:CXjg3Tig1mwccSKmdJjd3aofzJqI7veLOMIuFnxb9lA=,tag:eAkgT6e4FOmOtqLwfAAxTw==,type:str]
    RCLONE_CONFIG_PCLOUD_TYPE: ENC[AES256_GCM,data:2Fduo1Ha,iv:ecor2EDrYEq5SvzybSNF3KGmURi9z1DkIQY2vGbA9ZM=,tag:UFRuB06U1MNeiKzmG4J1hw==,type:str]
    RCLONE_CONFIG_PCLOUD_HOSTNAME: ENC[AES256_GCM,data:OJthBWENZLyPqZ3rr3c=,iv:1Hyq7EfF/8WcITAeTFLbb/ZHIby+1z9xQieKdDYEluw=,tag:1gAv2qEFN6jZu2lw1gVPlA==,type:str]
    RCLONE_CONFIG_PCLOUD_TOKEN: ENC[AES256_GCM,data:qFVeY1V80n59cP67WenhIcfC2BPxV5RFLRVt1ADDO6KpYY3ZOJAlM7UtwEC5GL3UZrLRJc4tLqBbMh6QU5ZGPD/Mpw2aYVWA38On/aWNCACcYYuyc23Zo5gjzs82RfMYnsKUpE2bvO4nToWXCexZk8dH7HZIMGN0iQalbBeL,iv:RRov2KLQjMRxeVnCSpXwIv9KS0mVyD+Vo/B0dwn5+9w=,tag:XWpSm6lqwtmqoecsJ+ageQ==,type:str]
sops:
    age:
        - recipient: age198qlalug6g4kvmp3xypzzsr5lvw36wexemc2jn220t29l7nak33qft2q7y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3dmM1Wi9uNEVuaU5QeWpu
            OWtOYytxVExiTmVzbFhhOCtJeTZ3b0pmVlNBCkt5OFFtcHZGbThSUlZZLzl6VUdX
            WHhwLzlFL2lMbmZ1VjViUDRWc0hvMkkKLS0tIHBuOUF1djRyaUtsSGwvOHBXc0gr
            OHIyNTZ6Z3JZendqa0R5akg4ZTZyK0EKHuCn8wCRMw4W0H1PpYtPHzfsB7EixEOR
            rraL/31GrAY0CbkkniY1dg14joNqlabQE3NMUtLHKwDWSkonnOIaCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T02:24:34Z"
    mac: ENC[AES256_GCM,data:5P6GNynwPAxZCrtZ75wmQ3LRy9wD6dwtsHjKNgdiPRDBSahe3vtaardvbjMw1v0G85H5icuIzzNeSEO6ujcNAhp8kp+WHOoib9jXfRcb5MLncMzi7MTjgW1/vCs4fZF4MyaALQ6XtPtZOvcp1caT3yvGtbYnmdmbkhPQoQZWE3I=,iv:yVW+5xilykl04Pzar7bgfsRkO70Jki1uQPWaNDKIWE8=,tag:fWjQA5k3GgaORCkb5CC5mw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.12.1
