apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: freshrss
resources:
  - namespace.yaml
  - pvc.yaml
  - freshrss-config-volsync-minio.secret.yaml
  - volsync.yaml
  - freshrss.yaml
  - ingress.yaml
