apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss-config-longhorn-v2
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Gi
