apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-config-volsync-minio
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ${VOLSYNC_BACKUP_MAIN_ACCESSKEY}
  AWS_SECRET_ACCESS_KEY: ${VOLSYNC_BACKUP_MAIN_SECRETKEY}
  RESTIC_PASSWORD: ${VOLSYNC_BACKUP_MAIN_ENCRKEY}
  RESTIC_REPOSITORY: s3:${VOLSYNC_BACKUP_MAIN_URL}/${VOLSYNC_BACKUP_MAIN_BUCKET}/nextcloud/volsync/config-volsync-minio
---
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-data-volsync-minio
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ${VOLSYNC_BACKUP_MAIN_ACCESSKEY}
  AWS_SECRET_ACCESS_KEY: ${VOLSYNC_BACKUP_MAIN_SECRETKEY}
  RESTIC_PASSWORD: ${VOLSYNC_BACKUP_MAIN_ENCRKEY}
  RESTIC_REPOSITORY: s3:${VOLSYNC_BACKUP_MAIN_URL}/${VOLSYNC_BACKUP_MAIN_BUCKET}/nextcloud/volsync/data-volsync-minio
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: nextcloud-config-minio-dest
spec:
  trigger:
    manual: restore-once
  restic:
    repository: nextcloud-config-volsync-minio
    destinationPVC: nextcloud-config
    copyMethod: Direct
    cacheCapacity: 10Gi
    cleanupCachePVC: false
    accessModes:
      - ReadWriteOnce
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: nextcloud-data-minio-dest
spec:
  trigger:
    manual: restore-once
  restic:
    repository: nextcloud-data-volsync-minio
    destinationPVC: nextcloud-data
    copyMethod: Direct
    cacheCapacity: 10Gi
    cleanupCachePVC: false
    accessModes:
      - ReadWriteOnce
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
