apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: overseerr
    namespace: media
spec:
    interval: 15m
    chart:
        spec:
            chart: seerr
            version: 14.1.0
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    releaseName: overseerr
    install:
        remediation:
            retries: 3
    upgrade:
        remediation:
            retries: 3
    values:
        credentials:
            ${VOLSYNC_BACKUP_MAIN_NAME}:
                accessKey: ${VOLSYNC_BACKUP_MAIN_ACCESSKEY}
                bucket: ${VOLSYNC_BACKUP_MAIN_BUCKET}
                encrKey: ${VOLSYNC_BACKUP_MAIN_ENCRKEY}
                name: ${VOLSYNC_BACKUP_MAIN_NAME}
                path: ""
                secretKey: ${VOLSYNC_BACKUP_MAIN_SECRETKEY}
                type: s3
                url: ${VOLSYNC_BACKUP_MAIN_URL}
        ingress:
            main:
                enabled: true
                ingressClassName: external
                hosts:
                    - host: see.${DOMAIN_0}
                      paths:
                        - path: /
                integrations:
                    certManager:
                        certificateIssuer: domain-0-le-prod
                        enabled: true
                    homepage:
                        enabled: false
                    traefik:
                        allowCors: false
                        enabled: false
                        entrypoints:
                            - websecure
        persistence:
            config:
                enabled: true
                type: pvc
                existingClaim: overseerr-config
                accessMode: ReadWriteOnce
                size: "100Gi"
                retain: true
        release_name: overseerr
