apiVersion: v1
kind: Secret
metadata:
    name: overseerr-config-volsync-pcloud
    namespace: media
type: Opaque
stringData:
    RESTIC_PASSWORD: ENC[AES256_GCM,data:0m+ikg5Dg/SuZQi06Gs4akpWE2k5A0vcgsPHUr4MoG7UZh0QdVPWIA==,iv:fIQcP4RQ97z/dlWOudq83KcdR8mf3/X+NPNXrqEuRRs=,tag:l5hlTT2qiFhcvTqZlXPCcw==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:MLqU9dtODYVz8/Kue1PqTX0IlGYQzv8ZJd0Zuy4fpFO5rANugAhsMpmufNmRidkMfaYjM/12NjpIWDFfFTskZom9l2iJrco1264HxQ==,iv:FA2azbXRs9aEF5shWIcvKMGAjjKbGa3iMW8GiJnfoCQ=,tag:NFyan5WCGtRkfjbfUxHE2Q==,type:str]
    RCLONE_CONFIG_PCLOUD_TYPE: ENC[AES256_GCM,data:IxWXMli8,iv:rN6MI3K0ofzUOz+0lol980KjMQNLAZ7kpvbVeKVcGMQ=,tag:oG/am4aRT1NGzuWqUYDW4w==,type:str]
    RCLONE_CONFIG_PCLOUD_HOSTNAME: ENC[AES256_GCM,data:glL35h3+ooPqaVcma9M=,iv:JZpbmeJbSY4f6G6EVPn3ZPEYvQTFODB1DEC+N+3sNf4=,tag:luyHLfYk6WGaAVoY7PZsgQ==,type:str]
    RCLONE_CONFIG_PCLOUD_TOKEN: ENC[AES256_GCM,data:DFZjF74Vq8TzqrFxOpc/pHKtc8/WeySoHJKUQWqwe2Fw6xmOi6muyqD2yMzpgoXihB/DtF6rQxhIlFCTEDRvfABEzPLXbbFel91WXCTW7NmXEv70lcDygeVslF/AA2B9RuVRxrLIPuBjvjRm6Nb+vv/TqQdpbnGuYnJOBnpJ,iv:WoqbAUkYobScdsFOX+mawrt50LYBGBHblsHCP2dXnWU=,tag:OKFbQ/5AnG4XOsb54e8aDg==,type:str]
sops:
    age:
        - recipient: age198qlalug6g4kvmp3xypzzsr5lvw36wexemc2jn220t29l7nak33qft2q7y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYU0U5d0M0UmYzaU1pVkFJ
            VllhLzdrWVI4bS83YkM4NloydktSQ0FWckdnCmJNNWRpTGlSaHo1cXo4bUxjSndJ
            TDk3a0cyYXpjSmZPVmtJZ0pOeHRmaEUKLS0tIFB1dlJQb0k2MW5RN2I3cjJldG04
            TG80MGExOTZEcTAvcEJTdDcxNWZENHMK0yc924Ly7/KaqHmPnLqUURQrgIIcpP5k
            4Cl/hmFdOL0i06/6aOOGPFulzdP8O/C8hZYN0FtQW+Et85zVfjKtBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T18:03:01Z"
    mac: ENC[AES256_GCM,data:YaY2jaPopD0JCrSSrb/qPc3xrLN4cM+a5MpwTtOZTkESAI58K8CTzp18CuCB2DYn+q0iVR5fo58XCot2gTOTH86ZDHJPus03yxgO4BnDiJExYIgLKiY0CdTZYq2e6Ft+jLASF+OI5Oal/M+Hwspn5DULrCa/3t0NP3omqYFhYE8=,iv:ngPAmOCZP6ynZTbs3sGBQRBREeLC7AwAVYB0nlo+2m0=,tag:0/MF+53FbRWKRCB3XszRwA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.12.1
