apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-config-volsync-pcloud
    namespace: media
type: Opaque
stringData:
    RESTIC_PASSWORD: ENC[AES256_GCM,data:C4RPGQY2x1CLcc5tJdnBssRlZphm/k4s6Ijjppyto2H1ytjZPwIiVA==,iv:xa4bCt7xEWtqLPHx/pe5mt6ubRRUEZKCqSlGFzIUIzM=,tag:vq7aSO8YpoTdQH5uneqcWg==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:w+wBHkbvFkquCz4AahrJDv1Asc2rERRZV1dGc6lv/SBLsEfjWlWVEUgq8oxsLKveteWEzsHGcCl7YOI4knbw5p4xQP+lw9xTs3Mb,iv:BSjZI4ouS1E1NISotuvwyoyJ/rHhA/4h8uTOwdoociM=,tag:+Ib7viHzpjfKlWWZ75pr/g==,type:str]
    RCLONE_CONFIG_PCLOUD_TYPE: ENC[AES256_GCM,data:PgKzb1nV,iv:tgC+EISzBgNce/BRt4rmYvLxOhjg8ZfIWy2F2X7twYM=,tag:sntqkTkNU+ONZotwAeWJNg==,type:str]
    RCLONE_CONFIG_PCLOUD_HOSTNAME: ENC[AES256_GCM,data:3ins7EtaTkcj+3/1cLg=,iv:PzIpfG7pT310dqHNeMlFk4pmvzkqNX2L5iLthBeQox4=,tag:j1fYzRp31Pt5JFRurIvMuw==,type:str]
    RCLONE_CONFIG_PCLOUD_TOKEN: ENC[AES256_GCM,data:opF9zGhVBgUYPxkRhjMGL/8Ib37JXMOwFkHC1oaiRs+nDQ19KYT7ChdYG/IcN9X+Isrp0ykIDdjwSmWD3LdvcTlreMiiIxNg7WRRCduWDUBfRBqvbdzk6oBqX9Y687ztFmVNAZ1y1IfzfaT6b0Lic8n94AmItFbvigBvrvtg,iv:GJl+t3mpmKFiUkt4CvJEZebgqcYdk8NpDXJdQKh1eco=,tag:DNtQ0SSv2ORTlgSAjtAX0A==,type:str]
sops:
    age:
        - recipient: age198qlalug6g4kvmp3xypzzsr5lvw36wexemc2jn220t29l7nak33qft2q7y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnQ3lqTUZJVjUyTm0zaXN4
            WXlZeTdQRlZBRHpJdzNiRWtkQ0ZXd1FIMmg0CjRGZEVJOW9CeWZ4REVZYlpiKzZi
            aFp0TXFNK1Z6VEpueUlvd3FzUmlSQ3MKLS0tIGdwZ25WTzVudUZETEtCdUV3ZXo3
            ZEtzNlBEUnUvY1gxZHlRa3NrQVFGNlEKq5sU8cNRF9a/bpmds5TIzunN3Yr1MObi
            JaBrVBvV1VBi+PzSReHZlWIUzFRfu4y8c6MxT2GH+thQosh/RcgF1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T17:48:22Z"
    mac: ENC[AES256_GCM,data:DcbUAbweEggA7S/NyqUrMi7GWx8KBumvIUcID1KRPuN6toi796c5urWe6G3/fc0x10kbIjrOqLizpc9Fd0xmSYDFyXGm/JRoGsIrc9eOrlEEIre2PXM1pKmy7Voc/MjoF9/gJWAsidJTBFGmIZy2B8/tcpT0I+nM2EAgDtfcknI=,iv:usqpJ4eSq/Nahza3iUp7Aknd4kJAGKnywzFqODVx9RE=,tag:YIX2QuI8XMlhVTkhuZoQhA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.12.1
