apiVersion: v1
kind: Secret
metadata:
    name: sonarr-config-volsync-pcloud
    namespace: media
type: Opaque
stringData:
    RESTIC_PASSWORD: ENC[AES256_GCM,data:yyxJuObjnnISxzz4jDzRn1g6SjUcMgdY/yUP2s6DN4YJHTfNWDaWZA==,iv:2Duthkb49R5IPZvqVVWd7FYzgGDY3c1DX9BkKW1srqA=,tag:QPuKG/G98nIWqzSwR+F+IA==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:4Wd3Z54IBIgVFbJ9oU1af31MJ6wTpIA0S3ZfHHCGEDv3jld/NCzff4LOqnYP4z1K+BvqI4S8IU0p0tCy5YITDSD1GtMlmxrXfg==,iv:NitBIabh/WAGWV44HS8XJVSoQqQpF9l+V8qaQ5SusQ8=,tag:Wc4JhIoC6cIIXfImL7LcqA==,type:str]
    RCLONE_CONFIG_PCLOUD_TYPE: ENC[AES256_GCM,data:7OLPvZLK,iv:vmjyUuGDRO2aCD1ALRqrPSg1VgVny5TPDkNj1gWEDKA=,tag:a3KtP3ghMfHZ1uqayxMr+Q==,type:str]
    RCLONE_CONFIG_PCLOUD_HOSTNAME: ENC[AES256_GCM,data:GzFgIpAgAIjNI8ZrC0Q=,iv:ZWsMx4XNQB4w9Y1Ig7x9pQtYLtctbUUVe0Xuc3Ogxjk=,tag:iL8A6i8DfAZEb479g0eP2g==,type:str]
    RCLONE_CONFIG_PCLOUD_TOKEN: ENC[AES256_GCM,data:sCBueqbmztteNbUVrmyndPwipVIXQ/9xrJggCuWngc8NYpA+U5AsjFUoBEMphSDirlx47Nalm7q0ab7Vqs16SQByYXXXZ76/ik51O//y3E0gqRsAIqyaNocBD4DsabRuCX/iZYcTklQr9jKBrGlksDNJ+I3B8u8ECBWI3g/E,iv:Pip2HWDUZ4bRhlNseuzzns1hO3w9/FsZUIOVeoyM8YY=,tag:8aveCxM2qjFMcWQE32UYUA==,type:str]
sops:
    age:
        - recipient: age198qlalug6g4kvmp3xypzzsr5lvw36wexemc2jn220t29l7nak33qft2q7y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwTk9IM1JXMWhtTUZ6UHlE
            VlVVRFEvZkJNNS9iSWZodnJUYmdZemNnT0dnClRLN0dRRXR0NDVDYjhWUTJicnlE
            SzVwbzh2enJtRFZwaXYwMUU3ZEZDajgKLS0tIEVpV0ZPU0xsVHFVcHE0WG9ha01T
            alk3cWlTdy9VZjVJUk5ia2pYc21TaTgKBEO30eecSHaiIOuMWGPyxWjoRQ+DnDDJ
            N/eRe2NwFxOVKHcpJ7DcxrPYs6TszVzdaBBwWyVupCKviwLaEctZiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T17:48:23Z"
    mac: ENC[AES256_GCM,data:4dspdeSvJQuFQJzNMM+bXox/R+JwrWuy+rPb+wSAesvX7rHwl4UVA2vt8a+/DF7rxQDJ6DosUfyagp6Vu9wkrgysJQthh+ogQmvc4tzldw7SOHUjOYx6O/LTjD0nJQkZhAKyjO0QSv8wlFlk3BZ2TseJW0LYo+52be8GMpplVGI=,iv:A0nwV/DCYCnT8CL1SaMV6rsVYzYsiV1uAFv+gL0JXWc=,tag:Cou2uiVpBTfqMmBN8x19Yg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.12.1
