apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-config-volsync-pcloud
    namespace: media
type: Opaque
stringData:
    RESTIC_PASSWORD: ENC[AES256_GCM,data:Hl+FuuMAxUSybyB/Qydm9PPmh7HbhK/6te1XV8QTwBP+uqxG1beRjw==,iv:+1oqPGP9Cc9IKoT7prhL9b4sbZ2BENY2ZlGMk8nd7SQ=,tag:di3IPbT7wVxKdykQ1cpVzg==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:r3NB9S33sJS6hRXVNySLYb2DSq63unEre5kSqCS9dBLL/0UBmynQxVkJabF6sl/qdPpavh00GSInOsu1sbUzcDaV0klLIBmBkysl0jlg,iv:tziQgv9FrgY5Oh0Tt7N/uQSwbFRh2Skmucnx3NBOc98=,tag:3IWHNYZDXfrJSfbs8WHfpA==,type:str]
    RCLONE_CONFIG_PCLOUD_TYPE: ENC[AES256_GCM,data:3DTP+bVd,iv:9P8bW9qXJCmEAWxZGizK0JXcr8iSqPS7Qmkpp6pDkbI=,tag:8cGaodcOBFFe/N7+VDEj8A==,type:str]
    RCLONE_CONFIG_PCLOUD_HOSTNAME: ENC[AES256_GCM,data:GAIK3OwuasE2pgAgeoc=,iv:TF65hY4yW7psnJR3v1BaVj60kkjMcZ5ojdMlwhA8y7g=,tag:+RvRezXGSKc59HGnEconRg==,type:str]
    RCLONE_CONFIG_PCLOUD_TOKEN: ENC[AES256_GCM,data:E9ykBpM++S8LX9bnX8OwraLiVAdqGx6jBNMZNpXGDkyUnkLl1LtnYAJAK6S0jZ4Tql0B9TgAoxWBC1mEhaXgn7goscyCtLOlmDCwl20TIlQtHnQYcXJMYnODI3BaWhiTkuhVplUtuq+BZjmx/lsZ7AyLytjFlAmod80VNgYa,iv:ichKGB8jtAx+QwvPmJlW2qgPA8MPEiWYlcYXdKeqe5M=,tag:T8SlDNoZiSfiM29JTDQbqg==,type:str]
sops:
    age:
        - recipient: age198qlalug6g4kvmp3xypzzsr5lvw36wexemc2jn220t29l7nak33qft2q7y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIWVVGOTdsZmdHeXBndDFk
            NGpkdDVBOWpmRkhVMnp0TXhFMS91Nk1ISUFNCjcxWFVXYW5PdWp3OWhwU1lVK0lr
            eTl2TVg1U29SbWRQVDdRNm4vWi9xQ1kKLS0tIEpxRnJUSGpzUmxtOXFvbHFZbm1Q
            eWFROXpRTXUralRON0tNQnhRVEtrTkEKhAPFJxEFJqj0WD7Yfx+FBsiCKiwEqEmO
            70vZ3FiQ9uCBFRuUFkOPVJWi3Xf0gcFjRyY04w6gzbeIYotOwxzQVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T18:03:01Z"
    mac: ENC[AES256_GCM,data:2tzJoQf5NHxOqyCwK2UWz6ixz9wKskbJbDC3SCclzVNHkgpB3tNXF+MYZ/95dJ1Vfv+V00GIlpJbV0sU3cfefqqnnR7hRNVTTh+6euvbWbR6eKb+9K2jPENziqwo0ayLKWnRAuBFH3VfSwy9N5ygR4UnkD403zj2G6QlqZWJzn8=,iv:6Ac+kxOWp9dhLtBHzqYrbsJ48jBq3phozHDCibGA+p8=,tag:c73iTqWjgKc+gVcqZtdTFw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.12.1
