apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minecraft
resources:
  - namespace.yaml
  - pvc.yaml
  - minecraft.yaml
  - ingress.yaml
  - minecraft-data-volsync-pcloud.secret.yaml
  - volsync-pcloud.yaml
