apiVersion: v1
kind: Secret
metadata:
    name: minecraft-data-volsync-pcloud
    namespace: minecraft
type: Opaque
stringData:
    RESTIC_PASSWORD: ENC[AES256_GCM,data:1w+euIvAlyj4at5IX2F+q3XtDpykLxhxiW/ybNPInbbX2F0BM3sc1w==,iv:zh/7A2i740HErmqvqWeN/VF6cSB16jt7TzemWRpkPcM=,tag:umbdV3gn+yhFD4bC1DyQjQ==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:BW/hYg/974nkOi0EzPQ2HiZY8jXnG7ktr2Lw+yLXp4t9X/RD2XzYTNy9qzqCbTYe42mtSgF3dnqr5zyq8s+of9nCSIYBBfKSMoU=,iv:P6yLdjdGFNovJxTzPDRgBEYkQyoquDUM7Fdorv41qJE=,tag:gQWYAS0zgQbvAmggmVU8yw==,type:str]
    RCLONE_CONFIG_PCLOUD_TYPE: ENC[AES256_GCM,data:+hS9s5g6,iv:AXx7oH7wWElAVUMZ0KidtOBvVJfa0lMF69hLsTUHIqo=,tag:VYEwptqIPea6J/0EiIsTww==,type:str]
    RCLONE_CONFIG_PCLOUD_HOSTNAME: ENC[AES256_GCM,data:D7dlGfSBZTVbjXuSIdk=,iv:tcXLsXMnxTg7OayvmriqWAPpRmESsCFr1AA/nJl6zbw=,tag:QGxXETqfkJYiaOQG/rnm9w==,type:str]
    RCLONE_CONFIG_PCLOUD_TOKEN: ENC[AES256_GCM,data:orU64WO66tJtaxp0PYHAtj2aCFAGkUg84/JAevkFPLLE/5SfLRDzW21k1pCH9vUIJll9rAXKIs/WKHdM61EV4MVTRNOhRpfv05yip4v0883UfQ9Gvy2o5pUinRXXsHjGICbXfrNFAGY9liTWUB018E98fTooTsa8eMYDXSHn,iv:TBFihCfOgfPBnp2lRlvUvlLibQhjse/PeTpmYAv9ayE=,tag:wMvklpm86OahUCgTyxP9oA==,type:str]
sops:
    age:
        - recipient: age198qlalug6g4kvmp3xypzzsr5lvw36wexemc2jn220t29l7nak33qft2q7y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhWjVSVVpXdU9oUjFtRjhm
            NkVwQ2FGZ0JWa1JjWkRnWWt4TnlyNWRuaUdJCkVJKzhPUGhlZmxvMCtVSmxzNE1v
            dDUwQSsyOWEvb2ZZTnEvaU9jbG5yNVUKLS0tIHc1cVYrMG1JWnFkK1k1MW1WOXov
            L0RXOEZSNTBjaXN2VENIeEI2bFV2bXMKxc+6sScw065dzlsg4owSiW6c3UvLEf/8
            msomSEMZcWCwUI3bHwshTcC+jiIQ0okvqdwRyxVeKO8UFD3c0y9tBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T17:48:23Z"
    mac: ENC[AES256_GCM,data:jQuYxkRI1puYibGP3AAgyqM/IScNRmv1MbeXNJG6V76W8jbzj35q74ksUX+uj0wVotH/kWUTAuWisP8fv+AMWZ5fmg6epc+NZqcDTXlQzcYlkM9OAZUn+kl+7HfmiV0K7OfuhDLAibIYPpqcye/U3t2aTo+v1e9q0dhJKfOT+yg=,iv:By8VB/2wORtI5SrBx8RSjLsF8Hlg2497Tf2422s1zw4=,tag:sshU6zEqbA2JMWn+1v2lgA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.12.1
