apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: romm
resources:
  - namespace.yaml
  - secrets.yaml
  - pvc.yaml
  - mariadb.yaml
  - romm.yaml
  - ingress.yaml
  - volsync.yaml
  - ../../../common/bw-auth-token
