apiVersion: v1
kind: Secret
metadata:
    name: romm-config-volsync-pcloud
    namespace: romm
type: Opaque
stringData:
    RESTIC_PASSWORD: ENC[AES256_GCM,data:kI5OhcQHnoDg/TPSyykvYCwOf14zD9IdcOF9/4D0haWYFrl6EfX2KA==,iv:BEeqp40B5xuvakD6Tkf7T/NcmNt4PUmjC1uPE0sA05M=,tag:TdJdBH8crWw55g9oXhwVaA==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:rZ096pDSDGY2mPrpxwq/5WxszASFlho43G1yOpCoiS5OzOJGFkonmCwx55MaNDlmeIC7CVnKNgT6DST6bgC+6DelbGkyZ/k=,iv:m1Et2BIYXXLdsL/2jiueEJwijJRoZVFi9iA8izLs5Qg=,tag:kvpYHXabjJT07IigfucBzw==,type:str]
    RCLONE_CONFIG_PCLOUD_TYPE: ENC[AES256_GCM,data:FHw48bq2,iv:DcR88XPpGg74dSvMy1n3Jkt+C3Ui5RmX2ZNNa4SkfAs=,tag:iT+L6/zjERSNFkliIJEJRQ==,type:str]
    RCLONE_CONFIG_PCLOUD_HOSTNAME: ENC[AES256_GCM,data:uu0bRhVYXXhRsYgwris=,iv:T/Z2xSgVC0jCLfr2/16vRcO0k9Vq5COpAGuXk0mITPg=,tag:f/YDxbAbvVWYtjyQiEF3NA==,type:str]
    RCLONE_CONFIG_PCLOUD_TOKEN: ENC[AES256_GCM,data:NLsg6LQuAWzz0UC/qYKJFwdNhWyvnvlPymuZGJ0o8PUmZqvjtAv0R5z7nz/zZg1L7QgiFmj33ONf3oLedeTD+bszaF9I/S4AZg9L9nnwtkd7Gb3vig5REvApMgO7+RdB3CNCoe6oc7MfU9zbCDVLbVj8afn//DQonkSiv6ko,iv:isgd030H1lpqoSjGvGEYFMhEQgrL4lc4Bw9CsD4lTGU=,tag:DYMAcwkWfvJ1KAg9Yf/jgA==,type:str]
sops:
    age:
        - recipient: age198qlalug6g4kvmp3xypzzsr5lvw36wexemc2jn220t29l7nak33qft2q7y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4OExJelB3UlZGRWE2dDhO
            bWJzTXMzY29sZkZJSStqOSttblJJeTIzNG5vCmFuY2h4V3BCTDNCVXM4YjRxRWpZ
            NmpvLzlpR0VrelNiVlkrRXlXTjNJNjgKLS0tIFpZd0dWSGhBOHZyM1Z5MVR5eVVm
            eXptNGZ2ZUQ5cS9MKzdOWVBmMHhySkUKM5Fnw7PMkYt2pFqxMiMhetOvVc6IdnQq
            g9NpDdDGZ5wPPWk87lVraQZRXiD7XbwUp0DYSmZaUh5Qm8tk1X88Bw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T17:48:23Z"
    mac: ENC[AES256_GCM,data:7DLMaV8rBt1qJiwvCa6fwlBz6Tj8mQ18ro+be3Lgzrx3bNj1QdCbdo8/oN2TJ//6Ol1d5+qK0Mzil1hqwdPOApvm2W7rv2UJwbJzQ9tZNP9spECJgiGqgvaMbiqL1anBREtvXZb9z6ePCfAceTl3YXf2lua8Gu6nsJGjXbfmYAs=,iv:qTLh/GkDV3tGAystd8sESgJEfUve/ZaddLYd+hIIqkc=,tag:iiAdx9PXqLE2yAqlih8zxQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.12.1
