apiVersion: v1
kind: Secret
metadata:
    name: mealie-data-volsync-pcloud
    namespace: mealie
type: Opaque
stringData:
    RESTIC_PASSWORD: ENC[AES256_GCM,data:0u6bfGzKqRU+jYFjIDDUR5wAHkJVhsGr5RlhaPe8Gcmvd16+csi2nA==,iv:WJd6P/U6KrWCUW34S8ot+5ctCXyE/UtnxU8SkUXH8dE=,tag:tXse2O1rNs7ZLSVaAMapRw==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:jDhLtmKC9aS01xDspT+JB5wMm0u0G+EFlOGLH3SKLoKGZnq1qSOmgVoQ9uoK0EBm/QG+WLHzVeRTyZmnDVcs229SB0cjS5E=,iv:H42K3JRRqkIhXLw5vW/rP9wkgseGsJ7qTgcJetsh9dg=,tag:05ehbiM79XH+r06qmsCWLQ==,type:str]
    RCLONE_CONFIG_PCLOUD_TYPE: ENC[AES256_GCM,data:t/DRXaOH,iv:tSRnjamo3KQ51EIU/SK5xYjYIpWPd645QGkxh6K9NiI=,tag:HYvbASLsmNqF4Y3cvRdF3Q==,type:str]
    RCLONE_CONFIG_PCLOUD_HOSTNAME: ENC[AES256_GCM,data:H3tRpJjrBTTePo4upgs=,iv:Xz8wfS+41HNTifpyxzQWcGgqLEfwmieTcNZVuEJyQs0=,tag:dQpelbz8+JqMb7cv2NPekg==,type:str]
    RCLONE_CONFIG_PCLOUD_TOKEN: ENC[AES256_GCM,data:9xBkUuh+hHQ+rpvQ3xJK8V6gqFZJAaUy3NWrnvAanxKAOX3zzRzDstrsPR0q/dheeaVinTQrWnc9REUCtkNmfLYArimo0m/KrrMoNc09aFxyFicDZjsFg/mfD18HskwcaYMXg38QFKQWVexGS82Grw7yxhIQlhdTZ7rxEikn,iv:hml+ZNLDHkQEY/XZbq2mSLm6OJYCTICPNi/5sLXHYfA=,tag:B3lRlQY55ZQrMCw5B3tvWg==,type:str]
sops:
    age:
        - recipient: age198qlalug6g4kvmp3xypzzsr5lvw36wexemc2jn220t29l7nak33qft2q7y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ZmNqSGNzZUZPa2J6SzRF
            R2pQT1NWU0JyaGQ1T2RFSFdKVU8rZ3QrSGxnCnpxOUd3OEJ5Ym93T2pzNnlydkdT
            Y1BBVUFpL3I1SXk2OUFyZXVuVUUvdWMKLS0tIFRMRDgzK1V5M1hid3FlaTErd0ww
            N09TT2N3OWR2STgreGY4a1ppSDc4azgKdrDMAIb/teDIR5DmvTF30287G98LtbVi
            /VrqBTcakwkazxFMvoQL6GeM0vOquZOlUSKjiRAnOL6zs7kRtdkhWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T18:03:00Z"
    mac: ENC[AES256_GCM,data:wGRhe1MSE/pBszp2Ml41iV3jazxadFoyVghNrE4JT1zgIRmayyMw9JMfrHrDi7mWakVwOqfnLKSgxOwlg9KYykcbdhleDMGytaxczg6ScFYygsfQlLriU46I7hB2qthnkt7ER5kHm5ViOrVqruvFU5Hxw3mnz4EjkVPDZt5iXtI=,iv:zpwIB0MH0MMP6bQJwyoAimV3qKcB5hHPQNKT4B6qepA=,tag:wOWt3yBmw04ddHrf2APJYg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.12.1
