apiVersion: v1
kind: Secret
metadata:
  name: rsshub-rediscreds
stringData:
  plainhost: rsshub-redis
  plainport: "6379"
  host: rsshub-redis.rsshub.svc.cluster.local
  port: "6379"
  password: ""
  url: redis://rsshub-redis:6379
type: Opaque
