apiVersion: v1
kind: Secret
metadata:
    name: lidarr-config-volsync-pcloud
    namespace: media
type: Opaque
stringData:
    RESTIC_PASSWORD: ENC[AES256_GCM,data:KiW/LAh1gyiyzIyBqYK04W+WW47BYwva+hmNp9g4HTN1I78DFT5sDA==,iv:gNfAQtzx9oUEfOXnHWHXRRJOIGMPuOecmwc4Bdsl4PY=,tag:w3c2QOyqCjTb+sAHbE0org==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:3HwBQ6TSHcKnAo3OXLYSba6Ew052hIE7jVlH0lRx5ibVasLnCNsY2hNySvptAApKNx/u8cZn0h/rpgGAZk94uWal2OFsiLBdUw==,iv:hw0HvvRBfG543c2oqHrGFxf0wPnorWuhOZNUWbJwWJw=,tag:ro/nGSeGyBRJ7twrSbKl+Q==,type:str]
    RCLONE_CONFIG_PCLOUD_TYPE: ENC[AES256_GCM,data:y7hjBb9y,iv:sB2ovkUTFV7ZARIIlVkSnnA5w1rld43u6JnE9C/ilts=,tag:Y9uXsrexvVhr69JMnbk/og==,type:str]
    RCLONE_CONFIG_PCLOUD_HOSTNAME: ENC[AES256_GCM,data:ncPFSYuObD4452LDazA=,iv:JPI8IOVvLf+irhEBFuWf8MP1q6T4qqQEKGUTGFD9Mfw=,tag:eQ8czEXBoggS5lFNGVPoaQ==,type:str]
    RCLONE_CONFIG_PCLOUD_TOKEN: ENC[AES256_GCM,data:FmPOrgXjKC7W94JFKqPmfO+YSzGOIX6G0A87iYMNsFcHG79CQARMDaAYAZ6GqclfOUDDqT25T+DJMVKMZLrJCGJnQp37/CP1AiY994bQ1ST1BCcL37xYxsE/dGGSWdyktz1jve61SjEwfso59wBA3vLvnDCBOOBPx6xSgmiR,iv:1lrMluQQfSfWKZ23OaatoHO/CLry9/iJP8Nr5P2QI2E=,tag:kQ3WfUePX22kJZ9SALP0ug==,type:str]
sops:
    age:
        - recipient: age198qlalug6g4kvmp3xypzzsr5lvw36wexemc2jn220t29l7nak33qft2q7y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4TWx3QlZSQ0dKdTBVNEdz
            SmRNdEhycXo2NEsvSko2cjNTS09BS0w3a25FClkyYjFsTGFyc0pMS1FMZ1dqL3FP
            cERzZFVRZVpnMENmR1JsUjVCVEJwdnMKLS0tIEkvd1NVNHM3WnRXd3gvbUhPRktH
            SjQyVmV4ckN1aWVWYzNYYnFud2FNK0UKY7I3OCreRBSFejE2Pkw/jlgn5Ad3xxMY
            yDFlOQkM8t7OMooc4/WCozb78RmkPEpxND0K8iq2jJtLX5T0Ck3kGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T17:48:22Z"
    mac: ENC[AES256_GCM,data:eE1SxXDkW7WIR1OrgNC3+4ulMzfojK07z/aKAREH6d0kGHH8ll0t0DxDOMj7mR3r/jOr7Gp5no71JyrMYORH1ImOirnzj/AuT5VQBnDV18CIhM1dAF/k0kLLp5B6SnC0ZPiTxkWEDaiA0LKS9TdA38yaonsVIjUJ+cIxdpU2lCM=,iv:E0k9S/DCfEXOWyWO2REUkWXSE295Y4OXTeAa2VAhXVU=,tag:5n1WtN33L8+peAARfgB7hQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.12.1
