apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: lidarr-config-pcloud
spec:
  sourcePVC: lidarr-config-longhorn-v2
  trigger:
    schedule: "30 4 * * *"
  restic:
    repository: lidarr-config-volsync-pcloud
    copyMethod: Direct
    pruneIntervalDays: 7
    cacheCapacity: 10Gi
    retain:
      daily: 3
      weekly: 4
      monthly: 2
      within: 30d
    accessModes:
      - ReadWriteOnce
    moverSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 568
