apiVersion: v1
kind: Secret
metadata:
    name: alist-data-volsync-pcloud
    namespace: alist
type: Opaque
stringData:
    RESTIC_PASSWORD: ENC[AES256_GCM,data:nLYh7/oog+cZJyum02CmJnmRtig0Kbvrs2vCezhNT6Rlgg+9aYQ8pg==,iv:p4UmQvWofUudOfSAfFIwjVkalhaS1vLxaLA/P7UT12A=,tag:ejO+DlS9pClzSDtVbfdLeg==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:uX6IvN38PTnNJ0EMnIpmaB/KsdWNjRZjIPZc5JZYzYVMF4S3dO4y2Rku+lf9v9vghvrqhgFpjrc6UUabOSf4/JJr0bTeUA==,iv:aMNntcMy0TTdm5EBSd3E95hwLwYIvqdPYIgPPcTK/hs=,tag:CAZ8HxQRtJKocVVef3fkZA==,type:str]
    RCLONE_CONFIG_PCLOUD_TYPE: ENC[AES256_GCM,data:F/GPFPNK,iv:9+jO1Px1Wtf479mVHDc+/A23VSs14Pkw27bXLyknO7A=,tag:t5isnSdZy/0SP8MLvEx1qw==,type:str]
    RCLONE_CONFIG_PCLOUD_HOSTNAME: ENC[AES256_GCM,data:+eTcqNliByWWWIoJ/go=,iv:+4nf8ZuQFk/i3F+KTSED7o0/Ali7as0Pe5RoqIcv8b0=,tag:k32kMQkD/+CYM2jZgYVa3Q==,type:str]
    RCLONE_CONFIG_PCLOUD_TOKEN: ENC[AES256_GCM,data:zWnDuKFHTnXvrOQtDMs+kZ2QDIj791HSmTJggTxuSu9aEjIgKGM97CJ+JQTMsgDpzm9PAdEvwcD0zkojir07B7V9Gc32Yl7z2XJHlu+na0Q9pmpEfOhfQGEQtHIdMYDmuuwaa6P7UoZSVn5WO7eRm2PznX6VpSjuF42QE6C+,iv:mFYXXBV6IXsrWGVTI4q186jms27qf2cIBKW2z2fHLjI=,tag:1Zcc/QXTPdUi/Ujq3gCWQA==,type:str]
sops:
    age:
        - recipient: age198qlalug6g4kvmp3xypzzsr5lvw36wexemc2jn220t29l7nak33qft2q7y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSWhtbDVtUnVmamM2SVB3
            Q1UxVnhFVWV5RStGVE1hdmZhS05sNWNMcmowCmxKdHVGT2VPYXNBNEZHUUJkNGdK
            NkZYZEczbGFaS3JVeW5ya1JPN1lYYXMKLS0tIFNmNnlFMm5xVHQxY1VpdVhCZmJV
            RVJVMzZpbTEvU0xJeDNPTExCYXNaekUKq2AV6lq6poJAMBjO5qXSM98wuKzYjOGD
            wM4ARpzjc0U4KdgJXYjbbWzpkkA19Kc2dMfssOWlATqjhColFpKUOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T18:03:00Z"
    mac: ENC[AES256_GCM,data:QxRv0e2J8nFwdd/tXzIBQBTenlG75CU/UPGZ9p8Oryp5HZ2G8sYNI9kifHB02vv3jXFxIVoDrZHHafnIR7TblGNwhaetZQGq6fJKELNh2YWTS9N7LawKYqbl7AHydErwjY0urTJBKlA6KZ6TdtDBXCO/aOWYnVxN8erUyJKUYl0=,iv:dCr/0N9URWxyatmoWIfezmjw8j8lGXOrMgmPB69cMDw=,tag:O/SD7Lc5ozUFTdJI5O6/jA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.12.1
