apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alist-data
  namespace: alist
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Gi
